---
- name: Generate Terraform file from Jinja2 templates
  hosts: localhost
  vars_files:
    - vars/main.yml
  tasks:
    - name: Ensure dir output exists
      ansible.builtin.file:
        path: output/common
        state: directory
        mode: '0755'
    - name: Ensure dir output exists
      ansible.builtin.file:
        path: output/secret
        state: directory
        mode: '0755'
    - name: Ensure dir output exists
      ansible.builtin.file:
        path: output/app
        state: directory
        mode: '0755'


    - name: Get list of template
      ansible.builtin.find:
        paths: templates/
        patterns: "*.tf"
      register: template_files

    - name: Genera domain-common
      template:
        src: "/common/{{ item.path }}"
        dest: "output/common/{{ item.path | basename }}"
      loop: "{{ template_files.files }}"
      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('\.tf$', ''))) | default(false) | bool

    - name: Genera domain-secret
      template:
        src: "/secrets/{{ item.path }}"
        dest: "output/secrets/{{ item.path | basename }}"
      loop: "{{ template_files.files }}"
      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('\.tf$', ''))) | default(false) | bool

    - name: Genera domain-app
      template:
        src: "/app/{{ item.path }}"
        dest: "output/app/{{ item.path | basename }}"
      loop: "{{ template_files.files }}"
      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('\.tf$', ''))) | default(false) | bool