---
- name: Generate Terraform file from Jinja2 templates
  hosts: localhost
  vars_files:
    - vars/main.yml
  tasks:
    - name: load statics variables
      ansible.builtin.include_vars:
        file: vars/statics.yml

    - name: load variables elaborations
      ansible.builtin.include_vars:
        file: vars/elaborations.yml

    - name: Ensure dir app output exists
      ansible.builtin.file:
        path: output/{{ domain_name }}-{{ item }}/env/dev
        state: directory
        mode: '0755'
      with_items:
        - app
        - common
        - secrets

    - name: Ensure dir secrets output exists
      ansible.builtin.file:
        path: output/{{ domain_name }}-secrets/secret/dev
        state: directory
        mode: '0755'

    - name: Get list of template common
      ansible.builtin.find:
        paths: templates/common
        patterns: "*.tf"
      register: template_files_common

    - name: Get list of template secrets
      ansible.builtin.find:
        paths: templates/secrets
        patterns: "*.tf"
      register: template_files_secrets

    - name: Get list of template app
      ansible.builtin.find:
        paths: templates/app
        patterns: "*.tf"
      register: template_files_app

    - name: Get list of symlink common
      ansible.builtin.find:
        paths: templates/common
        file_type: "link"
      register: symlink_common

    - name: Get list of symlink secrets
      ansible.builtin.find:
        paths: templates/secrets
        file_type: "link"
      register: symlink_secrets

    - name: Get list of symlink app
      ansible.builtin.find:
        paths: templates/app
        file_type: "link"
      register: symlink_app

    # COMMON folder
    - name: Genera domain-common
      template:
        src: "{{ item.path }}"
        dest: "output/{{ domain_name }}-common/{{ item.path | basename }}"
      loop: "{{ template_files_common.files }}"
      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('^\d+_|\.tf$', '')), errors='ignore', default='true') | default(true) | bool

    - name: Create common symlink
      ansible.builtin.file:
        src: "../../../scripts/{{ item.path | basename }}"
        dest: "output/{{ domain_name }}-common/{{ item.path | basename }}"
        state: link
        follow: false
        force: yes
      loop: "{{ symlink_common.files }}"

    - name: Genera domain-common env
      template:
        src: "{{ item.src }}"
        dest: "output/{{ domain_name }}-common/env/dev"
      with_filetree: templates/common/env

    # SECRETS folder
    - name: Genera domain-secret
      template:
        src: "{{ item.path }}"
        dest: "output/{{ domain_name }}-secrets/{{ item.path | basename }}"
      loop: "{{ template_files_secrets.files }}"
      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('^\d+_|\.tf$', '')), errors='ignore', default='true') | default(true) | bool

    - name: Create secret symlink
      ansible.builtin.file:
        src: "../../../scripts/{{ item.path | basename }}"
        dest: "output/{{ domain_name }}-secrets/{{ item.path | basename }}"
        state: link
        follow: false
        force: yes
      loop: "{{ symlink_secrets.files }}"

    - name: Genera domain-secrets  env
      template:
        src: "{{ item.src }}"
        dest: "output/{{ domain_name }}-secrets/env/dev"
      with_filetree: templates/secrets/env

    - name: Genera domain-secrets env secret
      template:
        src: "{{ item.src }}"
        dest: "output/{{ domain_name }}-secrets/secret/dev"
      with_filetree: templates/secrets/secret/dev

    # APP folder
    - name: Genera domain-app
      template:
        src: "{{ item.path }}"
        dest: "output/{{ domain_name }}-app/{{ item.path | basename }}"
      loop: "{{ template_files_app.files }}"
      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('^\d+_|\.tf$', '')), errors='ignore', default='true') | default(true) | bool

    - name: Create app symlink
      ansible.builtin.file:
        src: "../../../scripts/{{ item.path | basename }}"
        dest: "output/{{ domain_name }}-app/{{ item.path | basename }}"
        state: link
        follow: false
        force: yes
      loop: "{{ symlink_app.files }}"

    - name: Genera domain-app env
      template:
        src: "{{ item.src }}"
        dest: "output/{{ domain_name }}-app/env/dev"
      with_filetree: templates/app/env

#    - name: Genera domain-{{ item.path.split('/')[1] }}
#      template:
#        src: "{{ item.path }}"
#        dest: "output/{{ domain_name }}-{{ item.path.split('/')[1] }}/{{ item.path | basename }}"
#      loop: "{{ vars['template_files_' + item.path.split('/')[1] + '.files'] }}"
#      when: lookup('vars', 'include_' + (item.path | basename | regex_replace('\.tf$', ''))) | default(false) | bool


#    - name: "Genera domain-{{ item.split('/')[1] }} env"
#      template:
#        src: "{{ item }}"
#        dest: "output/{{ domain_name }}-{{ item.split('/')[1] }}/env/dev"
#      with_items:
#        - templates/app/env
#        - templates/common/env
#        - templates/secrets/env